---

- name: Install Nagios
  apt:  pkg={{ item }}
        state=present
        update_cache={{ nagios_apt_update_cache }}
        cache_valid_time={{ nagios_apt_cache_valid_time }}
  with_items:
      - apache2
      - apache2-mpm-prefork
      - nagios3
      - nsca
      - python-passlib  # Required for the htpasswd Ansible module
